# Generated by Django 4.2.6 on 2023-10-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_review', '0002_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='cover_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='show',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anime_review.shows'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anime_review.userprofile'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviewrelationship',
            name='show',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anime_review.shows'),
        ),
        migrations.AlterField(
            model_name='userreviewrelationship',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anime_review.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
