# Generated by Django 4.2.6 on 2023-11-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0003_shows_cover_art_alter_reviews_show_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(to='anime_review.categories'),
        ),
        migrations.AddField(
            model_name='userreviewrelationship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime_review.categories'),
        ),
    ]
