# Generated by Django 4.2.6 on 2023-11-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0004_categories_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='categories',
        ),
    ]
