# Generated by Django 4.2.6 on 2023-11-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0005_remove_userprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
