# Generated by Django 4.2.6 on 2023-11-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0006_remove_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='category',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime_review.categories'),
        ),
    ]
