# Generated by Django 4.2.6 on 2023-11-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
