# Generated by Django 4.2.6 on 2023-11-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0018_alter_reviews_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='show',
            new_name='shows',
        ),
    ]
